# **ÖDEV-2**

1-Numpy kütüphanesini import edin.

In [2]:
import numpy as np

2-1'den 5 e kadar (5 dahil) b isimli bir dizi oluşturun.

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

3- 20 adet 0'dan oluşan 4 x 5' lik dizi oluşturun.

In [3]:
np.zeros((4,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

4- 15 adet 7 sayısından oluşan diziyi 3x5 olarak yazın.

In [7]:
np.full((3,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

5- 10–70 e kadar 5 er artan sayıları yaz.

In [8]:
np.arange(10,70, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

6- 10–20 arasında 15 aynı uzaklıkta elemanı olan array oluşturun. (linspace metodunu kullanın.)

In [9]:
np.linspace(10,20,15)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

7- Rastgele sayılardan oluşan diziyi 3x5 boyutunda yazdır.

In [13]:
np.random.randint(0,10, (3,5))

array([[1, 2, 2, 9, 0],
       [4, 7, 2, 7, 3],
       [9, 1, 7, 0, 5]])

8- 5 elemanlı birim matris oluşturun. eye() metodu kullanın.

In [4]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9- 0'dan 24 e kadar array oluştur. Sonra reshape metodu ile 4x6 boyutu olarak yazın.

In [10]:
arr = np.arange(0,24)
arr.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

10- 0 ile 1 arasında rastgele 10 sayıdan oluşan bir array tanımlayın. Minimum ve maksimum değerleri bulun.

In [4]:
arr1 = np.random.rand(10)
arr1
print(min(arr1))
print(max(arr1))

0.0756526486283483
0.9816402836851049


11- 36 sayıdan oluşan rastgele sayılar 6x6' lık array olarak yazdırın.

In [5]:
arr2 = np.random.randint(36, size =(6,6))
arr2

array([[16,  1, 16, 16,  7, 21],
       [20, 30, 28,  5, 16, 11],
       [ 5, 11, 20, 13, 15, 29],
       [ 5,  3, 23, 18,  2, 17],
       [20,  9,  8,  7, 33, 14],
       [19,  8, 34,  2, 14, 27]])

12- 5.satırdaki elemanları gösteriniz.

In [6]:
arr2[4]

array([20,  9,  8,  7, 33, 14])

13- 6.satır ve 6.sutundaki elemanları gösteriniz.

In [7]:
print(arr2[5])
print(arr2[:, 5])

[19  8 34  2 14 27]
[21 11 29 17 14 27]


14-4.sutundaki tüm elemanları çekin.

In [8]:
arr2[:, 3]

array([16,  5, 13, 18,  7,  2])

15- For döngüsünü ve flat metodunu kullanarak satır satır elemanları yazdırınız.

In [21]:
for i in range(len(arr2)**2):
    print(arr2.flat[i])

16
1
16
16
7
21
20
30
28
5
16
11
5
11
20
13
15
29
5
3
23
18
2
17
20
9
8
7
33
14
19
8
34
2
14
27


16- 0 ile 1 aralığında bir array oluştur. Bu array değerini 5 ile çarpın.

In [3]:
arr3 = np.random.randint(10, size=(2,5))
arr3

array([[7, 2, 4, 1, 0],
       [1, 1, 0, 4, 3]])

16- Satırların toplam değeri nedir?

In [4]:
np.sum(arr3, axis=1)

array([14,  9])

17-Satırların standart sapma değeri nedir?

In [6]:
np.std(arr3, axis=1)

array([2.48193473, 1.46969385])

18-Satırların varyans değeri nedir?

In [7]:
np.var(arr3, axis=1)

array([6.16, 2.16])

19- Satırların transpoz değeri nedir?

In [8]:
arr3.transpose()

array([[7, 1],
       [2, 1],
       [4, 0],
       [1, 4],
       [0, 3]])